[package]
name = "terra-wm"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2"
smithay = { git = "https://github.com/Smithay/smithay", rev = "347b2b30225b0425f0b44dc4c590e768f7dbe73e", default-features = false, features = ["backend_winit", "backend_drm", "backend_gbm", "backend_libinput", "backend_session_libseat", "backend_udev", "desktop", "renderer_gl", "wayland_frontend"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
tempfile = "3"
wayland-client = "0.31"
wayland-protocols = "0.32"

[[example]]
name = "test_client"
